"""Persistence repository Protocols."""

from typing import Protocol

from src.game.domain.graph import Graph
from src.game.domain.memory import DialoguePair, LogEntry, TurnLogEntry
from src.game.domain.progress import GameProgress

class GraphRepo(Protocol):
    """Graph-native runtime persistence."""

    async def save_graph(self, game_id: str, graph: Graph) -> None: ...

    async def load_graph(self, game_id: str) -> Graph: ...

    async def save_progress(self, progress: GameProgress) -> None: ...

    async def load_progress(self, game_id: str) -> GameProgress: ...

    async def append_log_entries(
        self, game_id: str, entries: list[LogEntry]
    ) -> None: ...

    async def append_history_entries(
        self, game_id: str, entries: list[TurnLogEntry]
    ) -> None: ...

    async def append_dialogue_entries(
        self, game_id: str, entries: list[DialoguePair]
    ) -> None: ...

    async def load_log_entries(self, game_id: str) -> list[LogEntry]: ...

    async def load_history_entries(self, game_id: str) -> list[TurnLogEntry]: ...

    async def load_dialogue_entries(self, game_id: str) -> list[DialoguePair]: ...


class ScenarioRepo(Protocol):
    """Read-only scenario seed access."""

    async def profile_exists(self, profile: str) -> bool: ...

    async def list_profiles(self) -> list[dict]: ...

    async def read_world_md(self, profile: str, *, missing_ok: bool = False) -> str: ...

    async def read_start_json(self, profile: str) -> dict: ...

    async def read_player_template(self, profile: str) -> dict: ...

    async def load_seed_records(self, profile: str, kind: str) -> dict[str, dict]: ...
